//
//  Bubble1.cs
//  SnagScript
//
//  Created by B. Muth on 2016-05-28.
//  Copyright (c) 2016 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



using System;
using System.Drawing;
using Foundation;
using UIKit;
using CoreGraphics;

namespace SnagScript
{
    public class PatientIDCallout : NSObject
    {

        //// Initialization

        static PatientIDCallout()
        {
        }

        //// Drawing Methods

        public static void DrawPatientCallout(UIColor contrastFill)
        {
            //// Color Declarations
            var backgroundCallout = UIColor.FromRGBA(0.918f, 1.000f, 0.240f, 1.000f);
            var cameraLine = UIColor.FromRGBA(0.000f, 0.000f, 0.000f, 1.000f);
            var cameraInterior = UIColor.FromRGBA(1.000f, 1.000f, 1.000f, 1.000f);
            var whiteLens = UIColor.FromRGBA(1.000f, 1.000f, 1.000f, 1.000f);
            //var contrastBlue = UIColor.FromRGBA(0.000f, 0.235f, 1.000f, 0.617f);
			var contrastBlue = contrastFill;

            //// Bezier 6 Drawing
            UIBezierPath bezier6Path = new UIBezierPath();
            bezier6Path.MoveTo(new CGPoint(164.0f, 15.0f));
            bezier6Path.AddCurveToPoint(new CGPoint(120.51f, 75.0f), new CGPoint(164.0f, 15.0f), new CGPoint(111.24f, 39.18f));
            bezier6Path.AddLineTo(new CGPoint(151.07f, 75.0f));
            bezier6Path.AddCurveToPoint(new CGPoint(163.95f, 75.98f), new CGPoint(157.67f, 75.0f), new CGPoint(160.97f, 75.0f));
            bezier6Path.AddLineTo(new CGPoint(164.53f, 76.12f));
            bezier6Path.AddCurveToPoint(new CGPoint(172.88f, 84.47f), new CGPoint(168.41f, 77.54f), new CGPoint(171.46f, 80.59f));
            bezier6Path.AddCurveToPoint(new CGPoint(174.0f, 97.93f), new CGPoint(174.0f, 88.03f), new CGPoint(174.0f, 91.33f));
            bezier6Path.AddLineTo(new CGPoint(174.0f, 104.07f));
            bezier6Path.AddCurveToPoint(new CGPoint(173.02f, 116.95f), new CGPoint(174.0f, 110.67f), new CGPoint(174.0f, 113.97f));
            bezier6Path.AddLineTo(new CGPoint(172.88f, 117.53f));
            bezier6Path.AddCurveToPoint(new CGPoint(164.53f, 125.88f), new CGPoint(171.46f, 121.41f), new CGPoint(168.41f, 124.46f));
            bezier6Path.AddCurveToPoint(new CGPoint(151.07f, 127.0f), new CGPoint(160.97f, 127.0f), new CGPoint(157.67f, 127.0f));
            bezier6Path.AddLineTo(new CGPoint(31.93f, 127.0f));
            bezier6Path.AddCurveToPoint(new CGPoint(19.05f, 126.02f), new CGPoint(25.33f, 127.0f), new CGPoint(22.03f, 127.0f));
            bezier6Path.AddLineTo(new CGPoint(18.47f, 125.88f));
            bezier6Path.AddCurveToPoint(new CGPoint(10.12f, 117.53f), new CGPoint(14.59f, 124.46f), new CGPoint(11.54f, 121.41f));
            bezier6Path.AddCurveToPoint(new CGPoint(9.0f, 104.07f), new CGPoint(9.0f, 113.97f), new CGPoint(9.0f, 110.67f));
            bezier6Path.AddLineTo(new CGPoint(9.0f, 97.93f));
            bezier6Path.AddCurveToPoint(new CGPoint(9.98f, 85.05f), new CGPoint(9.0f, 91.33f), new CGPoint(9.0f, 88.03f));
            bezier6Path.AddLineTo(new CGPoint(10.12f, 84.47f));
            bezier6Path.AddCurveToPoint(new CGPoint(18.47f, 76.12f), new CGPoint(11.54f, 80.59f), new CGPoint(14.59f, 77.54f));
            bezier6Path.AddCurveToPoint(new CGPoint(31.93f, 75.0f), new CGPoint(22.03f, 75.0f), new CGPoint(25.33f, 75.0f));
            bezier6Path.AddLineTo(new CGPoint(92.57f, 75.0f));
            bezier6Path.AddCurveToPoint(new CGPoint(164.0f, 15.0f), new CGPoint(99.54f, 28.81f), new CGPoint(164.0f, 15.0f));
            bezier6Path.AddLineTo(new CGPoint(164.0f, 15.0f));
            bezier6Path.ClosePath();
            backgroundCallout.SetFill();
            bezier6Path.Fill();
            UIColor.LightGray.SetStroke();
            bezier6Path.LineWidth = 3.0f;
            bezier6Path.Stroke();


            //// Rectangle Drawing
            UIBezierPath rectanglePath = new UIBezierPath();
            rectanglePath.MoveTo(new CGPoint(78.58f, 94.56f));
            rectanglePath.AddLineTo(new CGPoint(81.54f, 94.56f));
            rectanglePath.AddCurveToPoint(new CGPoint(85.17f, 88.82f), new CGPoint(81.54f, 94.56f), new CGPoint(83.61f, 89.64f));
            rectanglePath.AddCurveToPoint(new CGPoint(97.07f, 88.82f), new CGPoint(86.72f, 88.0f), new CGPoint(96.04f, 88.41f));
            rectanglePath.AddCurveToPoint(new CGPoint(100.18f, 94.56f), new CGPoint(98.11f, 89.23f), new CGPoint(100.18f, 94.56f));
            rectanglePath.AddLineTo(new CGPoint(103.92f, 94.56f));
            rectanglePath.AddCurveToPoint(new CGPoint(107.05f, 94.75f), new CGPoint(105.53f, 94.56f), new CGPoint(106.33f, 94.56f));
            rectanglePath.AddLineTo(new CGPoint(107.2f, 94.78f));
            rectanglePath.AddCurveToPoint(new CGPoint(109.23f, 96.36f), new CGPoint(108.14f, 95.04f), new CGPoint(108.88f, 95.62f));
            rectanglePath.AddCurveToPoint(new CGPoint(109.5f, 98.9f), new CGPoint(109.5f, 97.03f), new CGPoint(109.5f, 97.65f));
            rectanglePath.AddLineTo(new CGPoint(109.5f, 107.66f));
            rectanglePath.AddCurveToPoint(new CGPoint(109.26f, 110.1f), new CGPoint(109.5f, 108.91f), new CGPoint(109.5f, 109.53f));
            rectanglePath.AddLineTo(new CGPoint(109.23f, 110.21f));
            rectanglePath.AddCurveToPoint(new CGPoint(107.2f, 111.79f), new CGPoint(108.88f, 110.94f), new CGPoint(108.14f, 111.52f));
            rectanglePath.AddCurveToPoint(new CGPoint(103.92f, 112.0f), new CGPoint(106.33f, 112.0f), new CGPoint(105.53f, 112.0f));
            rectanglePath.AddLineTo(new CGPoint(78.58f, 112.0f));
            rectanglePath.AddCurveToPoint(new CGPoint(75.45f, 111.81f), new CGPoint(76.97f, 112.0f), new CGPoint(76.17f, 112.0f));
            rectanglePath.AddLineTo(new CGPoint(75.3f, 111.79f));
            rectanglePath.AddCurveToPoint(new CGPoint(73.27f, 110.21f), new CGPoint(74.36f, 111.52f), new CGPoint(73.62f, 110.94f));
            rectanglePath.AddCurveToPoint(new CGPoint(73.0f, 107.66f), new CGPoint(73.0f, 109.53f), new CGPoint(73.0f, 108.91f));
            rectanglePath.AddLineTo(new CGPoint(73.0f, 98.9f));
            rectanglePath.AddCurveToPoint(new CGPoint(73.24f, 96.46f), new CGPoint(73.0f, 97.65f), new CGPoint(73.0f, 97.03f));
            rectanglePath.AddLineTo(new CGPoint(73.27f, 96.36f));
            rectanglePath.AddCurveToPoint(new CGPoint(75.3f, 94.78f), new CGPoint(73.62f, 95.62f), new CGPoint(74.36f, 95.04f));
            rectanglePath.AddCurveToPoint(new CGPoint(78.58f, 94.56f), new CGPoint(76.17f, 94.56f), new CGPoint(76.97f, 94.56f));
            rectanglePath.ClosePath();
            cameraInterior.SetFill();
            rectanglePath.Fill();
            cameraLine.SetStroke();
            rectanglePath.LineWidth = 2.0f;
            rectanglePath.Stroke();


            //// Oval Drawing
            var ovalPath = UIBezierPath.FromOval(new CGRect(83.5f, 95.5f, 15.0f, 14.0f));
            whiteLens.SetFill();
            ovalPath.Fill();
            cameraLine.SetStroke();
            ovalPath.LineWidth = 1.0f;
            ovalPath.Stroke();


            //// Oval 2 Drawing
            UIBezierPath oval2Path = new UIBezierPath();
            oval2Path.MoveTo(new CGPoint(87.0f, 102.5f));
            oval2Path.AddCurveToPoint(new CGPoint(90.5f, 99.0f), new CGPoint(87.0f, 100.57f), new CGPoint(88.57f, 99.0f));
            oval2Path.LineCapStyle = CGLineCap.Round;

            UIColor.LightGray.SetStroke();
            oval2Path.LineWidth = 1.0f;
            oval2Path.Stroke();


            //// Oval 3 Drawing
            UIBezierPath oval3Path = new UIBezierPath();
            oval3Path.MoveTo(new CGPoint(56.0f, 102.5f));
            oval3Path.AddCurveToPoint(new CGPoint(41.5f, 117.0f), new CGPoint(56.0f, 110.51f), new CGPoint(49.51f, 117.0f));
            oval3Path.AddCurveToPoint(new CGPoint(27.0f, 102.5f), new CGPoint(33.49f, 117.0f), new CGPoint(27.0f, 110.51f));
            oval3Path.AddCurveToPoint(new CGPoint(41.5f, 88.0f), new CGPoint(27.0f, 94.49f), new CGPoint(33.49f, 88.0f));
            oval3Path.AddCurveToPoint(new CGPoint(56.0f, 102.5f), new CGPoint(49.51f, 88.0f), new CGPoint(56.0f, 94.49f));
            oval3Path.ClosePath();
            whiteLens.SetFill();
            oval3Path.Fill();
            UIColor.Black.SetStroke();
            oval3Path.LineWidth = 2.0f;
            oval3Path.Stroke();


            //// Oval 4 Drawing
            UIBezierPath oval4Path = new UIBezierPath();
            oval4Path.MoveTo(new CGPoint(52.0f, 102.5f));
            oval4Path.AddCurveToPoint(new CGPoint(41.5f, 113.0f), new CGPoint(52.0f, 108.3f), new CGPoint(47.3f, 113.0f));
            oval4Path.AddCurveToPoint(new CGPoint(41.5f, 102.5f), new CGPoint(41.5f, 113.0f), new CGPoint(41.5f, 108.3f));
            oval4Path.AddCurveToPoint(new CGPoint(41.5f, 92.0f), new CGPoint(41.5f, 96.7f), new CGPoint(41.5f, 92.0f));
            oval4Path.AddCurveToPoint(new CGPoint(52.0f, 102.5f), new CGPoint(47.3f, 92.0f), new CGPoint(52.0f, 96.7f));
            oval4Path.ClosePath();
            contrastBlue.SetFill();
            oval4Path.Fill();


            //// Bezier 2 Drawing
            UIBezierPath bezier2Path = new UIBezierPath();
            bezier2Path.MoveTo(new CGPoint(140.64f, 93.62f));
            bezier2Path.AddLineTo(new CGPoint(142.2f, 99.0f));
            bezier2Path.AddLineTo(new CGPoint(147.65f, 100.54f));
            bezier2Path.AddLineTo(new CGPoint(154.66f, 93.62f));
            bezier2Path.AddCurveToPoint(new CGPoint(146.09f, 105.54f), new CGPoint(157.0f, 99.0f), new CGPoint(151.9f, 105.54f));
            bezier2Path.AddCurveToPoint(new CGPoint(141.95f, 104.7f), new CGPoint(144.62f, 105.54f), new CGPoint(143.22f, 105.24f));
            bezier2Path.AddCurveToPoint(new CGPoint(134.61f, 112.44f), new CGPoint(139.71f, 107.55f), new CGPoint(134.61f, 112.44f));
            bezier2Path.AddCurveToPoint(new CGPoint(131.29f, 114.0f), new CGPoint(134.61f, 112.44f), new CGPoint(132.63f, 114.0f));
            bezier2Path.AddCurveToPoint(new CGPoint(127.0f, 109.77f), new CGPoint(128.92f, 114.0f), new CGPoint(127.0f, 112.11f));
            bezier2Path.AddCurveToPoint(new CGPoint(129.05f, 106.16f), new CGPoint(127.0f, 108.24f), new CGPoint(127.82f, 106.91f));
            bezier2Path.AddCurveToPoint(new CGPoint(136.94f, 100.28f), new CGPoint(129.52f, 105.88f), new CGPoint(134.12f, 102.26f));
            bezier2Path.AddCurveToPoint(new CGPoint(135.57f, 95.15f), new CGPoint(136.07f, 98.77f), new CGPoint(135.57f, 97.02f));
            bezier2Path.AddCurveToPoint(new CGPoint(146.09f, 87.46f), new CGPoint(135.57f, 89.42f), new CGPoint(140.64f, 86.69f));
            bezier2Path.AddLineTo(new CGPoint(140.64f, 93.62f));
            bezier2Path.ClosePath();
            whiteLens.SetFill();
            bezier2Path.Fill();
            UIColor.Black.SetStroke();
            bezier2Path.LineWidth = 2.0f;
            bezier2Path.Stroke();
        }

        //// Generated Images

		public static UIImage ImageOfPatientCallout (UIColor clr)
		{
			UIGraphics.BeginImageContextWithOptions (new CGSize (188.0f, 138.0f), false, 0);
			PatientIDCallout.DrawPatientCallout (clr);

			UIImage imageOfPatientCallout = UIGraphics.GetImageFromCurrentImageContext ();
			UIGraphics.EndImageContext ();

			return imageOfPatientCallout;
		}
    }
}
